// SPDX-FileCopyrightText: (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0
//
// Flow D1 (discover) + D2 (token-based install), driven from the browser.
// NOTE: the Device Agent terminates real TLS with a self-signed local CA
// (see device-agent/pki/ca.crt, generated by gen_cert.py). A real browser
// will refuse this cert on first contact — per design doc §3.1.1, this CA
// is meant to be pre-installed into the OS/browser trust store by OEP
// Installer. For manual testing without that step, open
// https://127.0.0.1:47100/local/status directly once and accept the
// security exception, or launch the browser with certificate checks
// relaxed for 127.0.0.1. This mirrors the same loopback-cert issue flagged
// earlier in this project's design discussion — it is NOT solved by this
// reference implementation, only demonstrated.
async function checkDeviceAgent() {
  const box = document.getElementById("device-agent-status");
  try {
    const res = await fetch(`${DEVICE_AGENT}/local/status`, {
      headers: { Origin: window.location.origin },
    });
    if (res.ok) {
      box.textContent = "Device Agent: reachable (loopback, TLS OK)";
      box.className = "status-box ok";
      return true;
    }
    throw new Error(`status ${res.status}`);
  } catch (e) {
    box.textContent =
      "Device Agent: NOT reachable — " + e.message +
      " (did you run device_agent.py, and accept its self-signed cert once in this browser?)";
    box.className = "status-box bad";
    return false;
  }
}

async function loadCatalog() {
  const list = document.getElementById("catalog-list");
  list.innerHTML = "Loading...";
  try {
    const data = await apiFetch("/catalog");
    if (data.items.length === 0) {
      list.innerHTML = "<p>No listed apps yet. Onboard + approve one, or click Seed demo data.</p>";
      return;
    }
    list.innerHTML = "";
    for (const app of data.items) {
      const card = document.createElement("div");
      card.className = "app-card";
      card.innerHTML = `
        <h3>${app.name} <small>(${app.category})</small></h3>
        <p>${app.short_description || ""}</p>
        <p><em>by ${app.isv_org_name}</em></p>
        <button data-app-id="${app.id}">Install</button>
      `;
      card.querySelector("button").addEventListener("click", () => installApp(app.id));
      list.appendChild(card);
    }
  } catch (e) {
    list.innerHTML = `<p class="status-box bad">Failed to load catalog: ${e.message}</p>`;
  }
}

function log(msg) {
  const el = document.getElementById("install-log");
  el.textContent += msg + "\n";
}

async function installApp(appId) {
  const el = document.getElementById("install-log");
  el.textContent = "";
  log(`--- Install flow (D2) for app ${appId} ---`);

  const agentOk = await checkDeviceAgent();
  if (!agentOk) {
    log("Aborting: Device Agent not reachable.");
    return;
  }

  const detail = await apiFetch(`/catalog/apps/${appId}`);
  const version = detail.versions[detail.versions.length - 1];
  log(`Using latest listed version: ${version.version} (${version.id})`);

  const profileRes = await fetch(`${DEVICE_AGENT}/local/system-profile`, {
    headers: { Origin: window.location.origin },
  });
  const systemProfile = await profileRes.json();
  log(`Device Agent SystemProfile: ${JSON.stringify(systemProfile)}`);

  let installResp;
  try {
    installResp = await apiFetch("/install", {
      method: "POST",
      body: JSON.stringify({ app_version_id: version.id, system_profile: systemProfile }),
    });
  } catch (e) {
    if (e.message.includes("428")) {
      log("License not yet accepted — accepting now (flow D2 step 4b)...");
      await apiFetch(`/apps/${appId}/versions/${version.id}/accept-license`, { method: "POST" });
      installResp = await apiFetch("/install", {
        method: "POST",
        body: JSON.stringify({ app_version_id: version.id, system_profile: systemProfile }),
      });
    } else {
      throw e;
    }
  }
  log(`Cloud issued install_token (opaque, single-use, expires in ${installResp.expires_in}s)`);
  log(`Browser relays ONLY the token to the Device Agent over loopback — never a payload.`);

  const installReq = await fetch(`${DEVICE_AGENT}/local/install`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Origin: window.location.origin },
    body: JSON.stringify({ install_token: installResp.install_token, system_profile: systemProfile }),
  });
  const installBody = await installReq.json();
  if (installReq.status === 422 && installBody.status === "needs_input") {
    log(`Device Agent reports needs_input — missing settings: ${installBody.missing_settings.join(", ")}`);
    log("(In a full UI this would prompt the SI for these values and retry /install.)");
    return;
  }
  if (!installReq.ok) {
    log(`Device Agent rejected install: ${installReq.status} ${JSON.stringify(installBody)}`);
    return;
  }
  log(`Device Agent redeemed the token itself (its own outbound call to the Cloud) and applied the plan.`);
  log(`Result: ${JSON.stringify(installBody)}`);
}

document.addEventListener("DOMContentLoaded", () => {
  window.loadCatalog = loadCatalog;
  checkDeviceAgent();
  loadCatalog();
});
